threshold:
  #Thresholds for the color-indicator
  color:
    lime:
      min: -0.3
      max: 0.3
    green:
      min: -1
      max: 1
    yellow:
      min: -5
      max: 5
    orange:
      min: -10
      max: 10
beam:
  #Enable the particle beam
  enabled: true
  distance:
    #The initial distance away from the player
    start: 8
    #The total distance (determines the beam-length)
    total: 32
  #Distance between particles
  frequency: 2
titles:
  #Enable titles
  enabled: true
  direction:
    level: "--     --"
    up: "^      ^"
    down: "v       v"